# Generated by Django 4.1.7 on 2023-02-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can View History')]},
        ),
    ]
